name: 'Build style and deploy docker image'

on:
  push:

permissions:
  contents: write


jobs:
  build-css:
    runs-on: ubuntu-latest

    steps:
        #Checks-out the repository
      - name: Checkout source Git branch
        uses: actions/checkout@v4

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.6.0
        with:
          source: src/assets/styles/style.scss
          destination: src/assets/styles/style.css

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: css
          path: src/assets/styles/style.css

  build-and-push-image:
    needs: build-css
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      # 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: css
          path: src/assets/styles/

      # To enable multi-plateform build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: "pjezegou/defi-g1g2-website:latest"
